name = "Airstrike Pack"
author = "zentixua"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc3101997b36b38d75513fa5230fd1df780a95e3a4761b30ff1a46389b651c4d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
acceptable-game-versions = ["1.21"]
