name = "Airstrike Pack"
author = "zentixua"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e2b266c955892697ebd1d5111bd43540aad558e0822967bc2de83ae0e20de62"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
acceptable-game-versions = ["1.21"]
